// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTbxDqEvz2b219Gy5yJGuAZ_3n6u4GQHc',
    appId: '1:317921569929:web:0f536741091cd42faf6a58',
    messagingSenderId: '317921569929',
    projectId: 'smart-spark-api',
    authDomain: 'smart-spark-api.firebaseapp.com',
    storageBucket: 'smart-spark-api.appspot.com',
    measurementId: 'G-CX41Z4M79W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvYHYE_6Echrl1IRsONIRoGsOIDG77SiA',
    appId: '1:317921569929:android:c2f6b3cdebf8562faf6a58',
    messagingSenderId: '317921569929',
    projectId: 'smart-spark-api',
    storageBucket: 'smart-spark-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Dej-yh1aVJEQzvL3uxdxWrB0bL1531Y',
    appId: '1:317921569929:ios:faaac1582f0eeaebaf6a58',
    messagingSenderId: '317921569929',
    projectId: 'smart-spark-api',
    storageBucket: 'smart-spark-api.appspot.com',
    iosBundleId: 'com.example.smartspark',
  );
}
